"use client";

import React, { createContext, useContext, useEffect, useState, ReactNode } from "react";

type Lang = "pl" | "en";

type Dict = Record<string, string>;

const dictionaries: Record<Lang, Dict> = {
  pl: {
    // header
    "header.b2bOnly": "B2B only — zamówienia dla podmiotów gospodarczych",
    "header.b2bShort": "Tylko B2B",
    "header.categories": "Kategorie",
    "header.shippingCosts": "Koszty wysyłki",
    "header.terms": "Regulamin",
    "header.login": "Zaloguj się",
    "header.searchPlaceholder": "Szukaj — nazwa produktu, kategoria, SKU…",
    "header.search": "Szukaj",
    "header.cart": "Koszyk",
    "header.net": "netto",
    "header.netLong": "Podane ceny są netto",
    "header.loginBtn": "Zaloguj",
    "header.signup": "Rejestracja",
    "header.logout": "Wyloguj",
    "header.new": "Nowości",
    "header.sale": "Wyprzedaż",
    "header.bestsellers": "Bestsellery",
    "header.allCategories": "Wszystkie kategorie",
    "header.products": "Produkty",
    "header.deliveryNote": "Dostawa: do ustalenia • Podane ceny są",
    "header.all": "Wszystkie →",
    // homepage banner
    "home.bannerBusiness": "Informujemy, iż w naszej hurtowni mogą składać zamówienia tylko podmioty gospodarcze.",
    "home.bannerSuffix": "— Wzorzec CentrumHurt, nowocześnie. Weryfikacja B2B przy zamówieniu.",
    "home.becomeSeller": "Zostań sprzedawcą →",
    // hero
    "home.badge": "HURTOWNIA WÓLKA KOSOWSKA — ONLINE",
    "home.heroTitle1": "Hurt B2B.",
    "home.heroTitle2": "Packs, not pieces.",
    "home.heroDesc": "Nowoczesne CentrumHurt: czysty katalog, ceny pack netto + brutto, boczny panel subkategorii — szybciej, lżej, mobile-first.",
    "home.browseCategories": "Przeglądaj kategorie",
    "home.newBestsellers": "Nowości / Bestsellery",
    "home.delivery": "Dostawa: do ustalenia",
    "home.pricesNet": "Podane ceny są",
    // trust bar
    "home.trustShippingTitle": "Koszty wysyłki",
    "home.trustShippingDesc": "Do ustalenia • COD / faktura",
    "home.trustB2BTitle": "Tylko B2B",
    "home.trustB2BDesc": "Weryfikacja NIP — jak CentrumHurt",
    "home.trustNetTitle": "Ceny netto",
    "home.trustNetDesc": "Brutto = netto + VAT • pack pricing",
    // featured
    "home.featuredTitle": "Kategorie hurtowni",
    "home.featuredDesc": "Taxonomia CentrumHurt — nowoczesne karty, podgląd subkategorii.",
    "home.viewAll": "View all →",
    "home.viewAllPl": "Zobacz wszystkie →",
    "home.browseProducts": "Przeglądaj produkty",
    "home.subcategories": "subcategories",
    // arrivals
    "home.arrivalsTitle": "Nowości & Bestsellery",
    "home.arrivalsDesc": "Najnowsze pack-produkty — jak CentrumHurt “Nowości”.",
    // footer
    "footer.title": "Wholesale Marketplace",
    "footer.desc": "Wólka Kosowska inspired • modern B2B • pack-quantity cart • COD.",
    "footer.contact": "Kontakt",
    "footer.info": "Informacje",
    "footer.faq": "FAQ",
    "home.noCategories": "Brak kategorii — admin w /admin/categories.",
    // product card
    "product.noImage": "Brak zdjęcia",
    "product.noCategory": "Bez kategorii",
    "product.gross": "brutto",
    "product.net": "netto",
    "product.pack": "Pack",
    "product.out": "Brak",
    "product.available": "paczek dostępnych",
    "product.add": "Dodaj",
    "product.netPricesNote": "Ceny netto — dostawa do ustalenia",
    "search.noResults": "Brak produktów",
    "search.resultsFor": "Wyniki dla",
    "categorySidebar.title": "Kategorie hurtowni",
    "categorySidebar.all": "Wszystkie produkty",
    // generic
    "common.loading": "Ładowanie…",
    "common.allProducts": "Wszystkie produkty",
    "cart.title": "Koszyk",
    "cart.packs": "paczek",
    "cart.empty": "Twój koszyk jest pusty.",
    "cart.browse": "Przeglądaj kategorie",
    "checkout.shipping": "Adres dostawy",
    "checkout.codNote": "Płatność przy odbiorze / faktura",
    "product.homeAll": "Strona główna",
    // auth login
    "auth.login.title": "Zaloguj się na konto",
    "auth.login.or": "Lub",
    "auth.login.createAccount": "utwórz nowe konto",
    "auth.login.emailLabel": "Adres e-mail",
    "auth.login.emailPlaceholder": "Adres e-mail",
    "auth.login.passwordLabel": "Hasło",
    "auth.login.passwordPlaceholder": "Hasło",
    "auth.login.signIn": "Zaloguj się",
    "auth.login.signingIn": "Logowanie…",
    "auth.login.registerSeller": "Zarejestruj się jako sprzedawca",
    "auth.login.loading": "Ładowanie…",
    // auth signup
    "auth.signup.title": "Utwórz konto",
    "auth.signup.alreadyHave": "Masz już konto?",
    "auth.signup.signIn": "Zaloguj się",
    "auth.signup.fullNameLabel": "Imię i nazwisko",
    "auth.signup.fullNamePlaceholder": "Imię i nazwisko",
    "auth.signup.emailLabel": "Adres e-mail",
    "auth.signup.emailPlaceholder": "Adres e-mail",
    "auth.signup.passwordLabel": "Hasło",
    "auth.signup.passwordPlaceholder": "Hasło (min. 8 znaków)",
    "auth.signup.confirmPasswordLabel": "Potwierdź hasło",
    "auth.signup.confirmPasswordPlaceholder": "Potwierdź hasło",
    "auth.signup.registerAs": "Zarejestruj się jako",
    "auth.signup.buyer": "Kupujący",
    "auth.signup.seller": "Sprzedawca",
    "auth.signup.sellerNote": "Konta sprzedawców wymagają zatwierdzenia administratora. Po rejestracji poprosimy o dane firmy.",
    "auth.signup.creating": "Tworzenie konta…",
    "auth.signup.create": "Utwórz konto",
    "auth.signup.errorMismatch": "Hasła nie są zgodne",
    "auth.signup.errorLength": "Hasło musi mieć co najmniej 8 znaków",
    // auth register seller
    "auth.registerSeller.title": "Zarejestruj się jako sprzedawca",
    "auth.registerSeller.alreadyHave": "Masz już konto?",
    "auth.registerSeller.signIn": "Zaloguj się",
    "auth.registerSeller.accountInfo": "Dane konta",
    "auth.registerSeller.fullName": "Imię i nazwisko",
    "auth.registerSeller.fullNamePlaceholder": "Imię i nazwisko",
    "auth.registerSeller.email": "Adres e-mail",
    "auth.registerSeller.emailPlaceholder": "Adres e-mail",
    "auth.registerSeller.password": "Hasło",
    "auth.registerSeller.passwordPlaceholder": "Hasło (min. 8 znaków)",
    "auth.registerSeller.confirmPassword": "Potwierdź hasło",
    "auth.registerSeller.confirmPasswordPlaceholder": "Potwierdź hasło",
    "auth.registerSeller.businessInfo": "Dane firmy",
    "auth.registerSeller.businessName": "Nazwa firmy",
    "auth.registerSeller.businessNamePlaceholder": "Nazwa Twojej firmy",
    "auth.registerSeller.taxId": "NIP (VAT)",
    "auth.registerSeller.businessAddress": "Adres firmy",
    "auth.registerSeller.phone": "Numer telefonu",
    "auth.registerSeller.optional": "Opcjonalnie",
    "auth.registerSeller.notePrefix": "Uwaga:",
    "auth.registerSeller.note": "Konta sprzedawców wymagają zatwierdzenia administratora. Po wysłaniu zgłoszenie zostanie rozpatrzone. Otrzymasz powiadomienie o decyzji.",
    "auth.registerSeller.submitting": "Wysyłanie zgłoszenia…",
    "auth.registerSeller.submit": "Wyślij zgłoszenie",
    "auth.registerSeller.errorBusinessName": "Nazwa firmy jest wymagana",
    "auth.registerSeller.errorMismatch": "Hasła nie są zgodne",
    "auth.registerSeller.errorLength": "Hasło musi mieć co najmniej 8 znaków",
    // seller dashboard
    "seller.dashboard.panel": "Panel sprzedawcy",
    "seller.dashboard.approved": "Zatwierdzony sprzedawca",
    "seller.dashboard.signOut": "Wyloguj",
    "seller.dashboard.title": "Panel sprzedawcy",
    "seller.dashboard.welcome": "Witamy",
    "seller.dashboard.categories": "Kategorie",
    "seller.dashboard.categoriesDesc": "Przeglądaj taksonomię i zgłaszaj nowe kategorie.",
    "seller.dashboard.manageProducts": "Zarządzaj produktami",
    "seller.dashboard.manageProductsDesc": "Dodawaj, edytuj i zarządzaj katalogiem produktów.",
    "seller.dashboard.orders": "Zamówienia",
    "seller.dashboard.ordersDesc": "Przeglądaj i zarządzaj zamówieniami.",
    "seller.dashboard.businessProfile": "Profil firmy",
    "seller.dashboard.businessProfileDesc": "Zaktualizuj dane firmy.",
    "seller.dashboard.quickStats": "Szybkie statystyki",
    "seller.dashboard.totalProducts": "Wszystkie produkty",
    "seller.dashboard.pendingOrders": "Oczekujące zamówienia",
    "seller.dashboard.completedOrders": "Zrealizowane zamówienia",
    "seller.dashboard.revenue": "Przychód",
    // seller pending
    "seller.pending.notFound": "Nie znaleziono profilu sprzedawcy",
    "seller.pending.notFoundDesc": "Uzupełnij rejestrację sprzedawcy.",
    "seller.pending.registerSeller": "Zarejestruj się jako sprzedawca",
    "seller.pending.statusTitle": "Status zgłoszenia sprzedawcy",
    "seller.pending.businessInfo": "Dane firmy",
    "seller.pending.businessName": "Nazwa firmy",
    "seller.pending.taxId": "NIP",
    "seller.pending.phone": "Telefon",
    "seller.pending.businessAddress": "Adres firmy",
    "seller.pending.rejectionReason": "Powód odrzucenia",
    "seller.pending.nextSteps": "Następne kroki",
    "seller.pending.pendingReview": "Twoje zgłoszenie jest rozpatrywane przez administratora.",
    "seller.pending.notify": "Otrzymasz powiadomienie po podjęciu decyzji.",
    "seller.pending.reviewTime": "Typowy czas weryfikacji: 1-2 dni robocze",
    "seller.pending.approvedTitle": "Gratulacje! Twoje konto sprzedawcy zostało zatwierdzone.",
    "seller.pending.approvedDesc": "Możesz teraz korzystać z panelu sprzedawcy, aby zarządzać produktami i zamówieniami.",
    "seller.pending.goDashboard": "Przejdź do Panelu Sprzedawcy",
    "seller.pending.rejectedDesc1": "Twoje zgłoszenie nie zostało zatwierdzone. Sprawdź powód odrzucenia powyżej.",
    "seller.pending.rejectedDesc2": "Możesz złożyć nowe zgłoszenie z poprawionymi danymi.",
    "seller.pending.submitNew": "Złóż nowe zgłoszenie",
    "seller.pending.backHome": "← Wróć do strony głównej",
    "seller.pending.statusPending": "oczekujące",
    "seller.pending.statusApproved": "zatwierdzone",
    "seller.pending.statusRejected": "odrzucone",
    // seller products
    "seller.products.panel": "Panel sprzedawcy",
    "seller.products.dashboard": "Panel",
    "seller.products.products": "Produkty",
    "seller.products.categories": "Kategorie",
    "seller.products.title": "Moje produkty",
    "seller.products.desc": "Zarządzaj katalogiem — rozmiar packa, ceny, stany, zdjęcia.",
    "seller.products.addProduct": "+ Dodaj produkt",
    "seller.products.empty": "Brak produktów. Utwórz pierwszy produkt pack.",
    "seller.products.emptyAdd": "Dodaj produkt",
    "seller.products.thProduct": "Produkt",
    "seller.products.thCategory": "Kategoria",
    "seller.products.thPackPrice": "Pack i cena",
    "seller.products.thStock": "Stan",
    "seller.products.thStatus": "Status",
    "seller.products.thActions": "Akcje",
    "seller.products.noImg": "Brak zdjęcia",
    "seller.products.archivedLabel": "(zarchiwizowany)",
    "seller.products.pack": "Pack",
    "seller.products.net": "Netto",
    "seller.products.gross": "Brutto",
    "seller.products.vat": "VAT",
    "seller.products.toggleStock": "Zmień stan",
    "seller.products.active": "aktywny",
    "seller.products.archived": "zarchiwizowany",
    "seller.products.edit": "Edytuj",
    "seller.products.archive": "Archiwizuj",
    "seller.products.unarchive": "Przywróć",
    "seller.products.delete": "Usuń",
    "seller.products.confirmDelete": "Usunąć produkt? Tej akcji nie można cofnąć.",
    "seller.products.inStock": "w magazynie",
    "seller.products.outOfStock": "brak",
    "seller.products.stockIn": "in_stock",
    "seller.products.stockOut": "out_of_stock",
    // seller products new/edit
    "seller.products.new.panel": "Panel sprzedawcy",
    "seller.products.new.productsLink": "Produkty",
    "seller.products.new.back": "← Wróć do produktów",
    "seller.products.new.title": "Dodaj produkt",
    "seller.products.new.desc": "Ceny pack, kategoria, stan i zdjęcia. Sprzedawca musi być zatwierdzony.",
    "seller.products.new.createLabel": "Utwórz produkt",
    "seller.products.edit.title": "Edytuj produkt",
    "seller.products.edit.productsLink": "Produkty",
    "seller.products.edit.back": "← Wróć",
    "seller.products.edit.notFound": "Nie znaleziono",
    "seller.products.edit.saveLabel": "Zapisz zmiany",
    "seller.products.edit.loadingFailed": "Nie udało się załadować",
    // seller categories
    "seller.categories.panel": "Panel sprzedawcy",
    "seller.categories.dashboard": "Panel",
    "seller.categories.categories": "Kategorie",
    "seller.categories.signOut": "Wyloguj",
    "seller.categories.available": "Dostępne kategorie",
    "seller.categories.availableDesc": "Taksonomia jest zarządzana centralnie. Wybierz z drzewa przy wystawianiu produktów; zgłoś brakujące.",
    "seller.categories.total": "kategorii łącznie • ukryte nieaktywne",
    "seller.categories.requestTitle": "Zgłoś nową kategorię",
    "seller.categories.requestDesc": "Zaproponuj nową kategorię główną lub podkategorię. Administrator zweryfikuje.",
    "seller.categories.name": "Nazwa *",
    "seller.categories.namePlaceholder": "np. Narzędzia ogrodowe",
    "seller.categories.slug": "Slug (opcjonalnie, automatycznie z nazwy)",
    "seller.categories.slugPlaceholder": "narzedzia-ogrodowe",
    "seller.categories.parent": "Kategoria nadrzędna (puste dla głównej)",
    "seller.categories.topLevel": "— Główna —",
    "seller.categories.description": "Powód / opis",
    "seller.categories.descriptionPlaceholder": "Dlaczego ta kategoria jest potrzebna?",
    "seller.categories.submitting": "Wysyłanie…",
    "seller.categories.submit": "Wyślij zgłoszenie",
    "seller.categories.myRequests": "Moje zgłoszenia",
    "seller.categories.noRequests": "Brak zgłoszeń.",
    "seller.categories.under": "Pod",
    "seller.categories.topLevelLabel": "Główna",
    "seller.categories.rejected": "Odrzucone:",
    "seller.categories.nameRequired": "Nazwa jest wymagana",
    "seller.categories.requestSubmitted": "Zgłoszenie wysłane dla",
    "seller.categories.pendingApproval": "— oczekuje na zatwierdzenie administratora.",
    "seller.categories.signOutLabel": "Wyloguj",
    // buyer dashboard
    "buyer.dashboard.panel": "Wholesale Marketplace",
    "buyer.dashboard.signOut": "Wyloguj",
    "buyer.dashboard.heading": "Panel kupującego",
    "buyer.dashboard.welcome": "Witamy ponownie",
    "buyer.dashboard.browseProducts": "Przeglądaj produkty",
    "buyer.dashboard.browseProductsDesc": "Odkryj katalog hurtowy i znajdź produkty dla swojej firmy.",
    "buyer.dashboard.myOrders": "Moje zamówienia",
    "buyer.dashboard.myOrdersDesc": "Przeglądaj i śledź zamówienia.",
    "buyer.dashboard.accountSettings": "Ustawienia konta",
    "buyer.dashboard.accountSettingsDesc": "Zarządzaj profilem i preferencjami.",
    // buyer orders
    "buyer.orders.title": "Moje zamówienia",
    "buyer.orders.desc": "Zamówienia w packach • COD • statusy oczekujące → dostarczone",
    "buyer.orders.empty": "Brak zamówień.",
    "buyer.orders.browse": "Przeglądaj produkty →",
    "buyer.orders.order": "Zamówienie #",
    "buyer.orders.gross": "Brutto",
    "buyer.orders.net": "netto",
    "buyer.orders.ship": "Wysyłka:",
    "buyer.orders.pack": "pack",
    // admin dashboard
    "admin.dashboard.panel": "Panel administratora",
    "admin.dashboard.admin": "Admin",
    "admin.dashboard.signOut": "Wyloguj",
    "admin.dashboard.title": "Zatwierdzanie sprzedawców",
    "admin.dashboard.desc": "Przejrzyj i zatwierdź/odrzuć oczekujące zgłoszenia sprzedawców",
    "admin.dashboard.manageCategories": "Zarządzaj kategoriami →",
    "admin.dashboard.noPending": "Brak oczekujących sprzedawców",
    "admin.dashboard.allReviewed": "Wszystkie zgłoszenia zostały rozpatrzone.",
    "admin.dashboard.thBusiness": "Nazwa firmy",
    "admin.dashboard.thApplicant": "Wnioskodawca",
    "admin.dashboard.thEmail": "E-mail",
    "admin.dashboard.thApplied": "Data zgłoszenia",
    "admin.dashboard.thStatus": "Status",
    "admin.dashboard.thActions": "Akcje",
    "admin.dashboard.approve": "Zatwierdź",
    "admin.dashboard.reject": "Odrzuć",
    "admin.dashboard.approving": "Zatwierdzanie…",
    "admin.dashboard.rejecting": "Odrzucanie…",
    "admin.dashboard.rejectionPrompt": "Podaj powód odrzucenia:",
    "admin.dashboard.approveFailed": "Nie udało się zatwierdzić sprzedawcy:",
    "admin.dashboard.rejectFailed": "Nie udało się odrzucić sprzedawcy:",
    // admin categories
    "admin.categories.panel": "Panel administratora",
    "admin.categories.sellers": "Sprzedawcy",
    "admin.categories.categories": "Kategorie",
    "admin.categories.signOut": "Wyloguj",
    "admin.categories.treeTitle": "Drzewo kategorii",
    "admin.categories.topLevel": "+ Główna",
    "admin.categories.edit": "Edytuj",
    "admin.categories.subcategory": "+ Podkategoria",
    "admin.categories.delete": "Usuń",
    "admin.categories.confirmDelete": "Usunąć kategorię? Nie można cofnąć, jeśli nie ma dzieci/produktów.",
    "admin.categories.editCategory": "Edytuj kategorię",
    "admin.categories.newCategory": "Nowa kategoria",
    "admin.categories.name": "Nazwa *",
    "admin.categories.slug": "Slug (auto jeśli puste)",
    "admin.categories.slugAuto": "elektronika",
    "admin.categories.parent": "Nadrzędna",
    "admin.categories.topLevelOption": "— Główna —",
    "admin.categories.active": "Aktywna",
    "admin.categories.save": "Zapisz",
    "admin.categories.create": "Utwórz",
    "admin.categories.cancel": "Anuluj",
    "admin.categories.pendingTitle": "Oczekujące zgłoszenia kategorii",
    "admin.categories.pendingDesc": "Sprzedawcy zgłaszają nowe kategorie/podkategorie; zatwierdź, aby dodać do drzewa.",
    "admin.categories.noPending": "Brak oczekujących zgłoszeń.",
    "admin.categories.approve": "Zatwierdź",
    "admin.categories.reject": "Odrzuć",
    "admin.categories.rejectionReason": "Powód odrzucenia:",
    "admin.categories.recentDecisions": "Ostatnie decyzje",
    "admin.categories.by": "przez",
    "admin.categories.topLevelFallback": "(główna)",
    // cart
    "cart.emptyTitle": "Twój koszyk jest pusty.",
    "cart.countPacks": "packów",
    "cart.packQuantityBased": "Ilość w packach. Kupujesz packi, nie sztuki.",
    "cart.pack": "Pack",
    "cart.gross": "brutto",
    "cart.net": "netto",
    "cart.remove": "Usuń",
    "cart.netTotal": "Suma netto",
    "cart.grossTotal": "Suma brutto",
    "cart.codNoteDetail": "Z VAT. COD / faktura ręczna dla MVP — brak bramki płatności.",
    "cart.proceedCheckout": "Przejdź do kasy",
    "cart.continueShopping": "Kontynuuj zakupy",
    "cart.noImg": "Brak zdjęcia",
    "cart.vatNote": "W tym VAT. COD / faktura ręczna",
    // checkout
    "checkout.title": "Kasa",
    "checkout.codDesc": "COD / faktura ręczna — brak bramki płatności dla MVP.",
    "checkout.cartEmpty": "Koszyk pusty.",
    "checkout.browseProducts": "Przeglądaj produkty →",
    "checkout.errorCartEmpty": "Koszyk pusty",
    "checkout.errorAddress": "Adres wysyłki wymagany",
    "checkout.errorBuyerOnly": "Tylko kupujący mogą składać zamówienia. Przełącz konto na kupującego.",
    "checkout.signInPrompt": "Zaloguj się jako kupujący, aby złożyć zamówienie. Możesz uzupełnić adres i zalogować się później.",
    "checkout.signIn": "zaloguj się",
    "checkout.shippingAddress": "Adres wysyłki *",
    "checkout.shippingPlaceholder": "Ulica, miasto, kod, kraj",
    "checkout.notes": "Uwagi (opcjonalnie)",
    "checkout.notesPlaceholder": "Uwagi do dostawy, prośba o fakturę…",
    "checkout.net": "Netto",
    "checkout.grossCOD": "Brutto (COD)",
    "checkout.payNote": "Zapłacisz przy odbiorze / faktura ręczna. Status zamówienia: oczekujące.",
    "checkout.placing": "Składanie…",
    "checkout.placeOrder": "Złóż zamówienie —",
    "checkout.codSuffix": "COD",
    "checkout.orderSummary": "Podsumowanie —",
    "checkout.itemsPackBased": "produktów, ilość w packach",
    "checkout.editCart": "Edytuj koszyk",
    // checkout success
    "checkout.success.title": "Zamówienie złożone",
    "checkout.success.desc": "Dziękujemy — COD/faktura ręczna. Status: oczekujące.",
    "checkout.success.order": "Zamówienie #",
    "checkout.success.totalNet": "Suma netto:",
    "checkout.success.totalGross": "Suma brutto:",
    "checkout.success.shipping": "Wysyłka:",
    "checkout.success.continueShopping": "Kontynuuj zakupy",
    "checkout.success.myOrders": "Moje zamówienia",
    "checkout.success.loading": "Ładowanie…",
    // search
    "search.titleSearch": "Szukaj:",
    "search.titleAll": "Wszystkie produkty",
    "search.desc": "Szukaj po nazwie, opisie, kategorii — proste ILIKE (gotowe na full-text Postgres).",
    "search.searching": "Wyszukiwanie…",
    "search.noResultsFor": "Brak wyników dla",
    // categories page
    "categories.allTitle": "Wszystkie kategorie",
    "categories.allDesc": "Przeglądaj według kategorii — boczny panel podkategorii jak centrumhurt.pl.",
    "categories.subcategoriesLabel": "podkategorii",
    "categories.allProductsTitle": "Wszystkie produkty",
    "categories.loading": "Ładowanie…",
    // categories slug
    "categories.slug.breadcrumbCategories": "Kategorie",
    "categories.slug.packPricing": "Ceny pack • netto/brutto • VAT wliczony",
    "categories.slug.productsCount": "produktów",
    "categories.slug.noProducts": "Brak produktów w tej kategorii.",
    "categories.slug.categoryNotFound": "Nie znaleziono kategorii",
    "categories.slug.allCategories": "← Wszystkie kategorie",
    // products detail
    "products.detail.breadcrumbCategories": "Kategorie",
    "products.detail.noImage": "Brak zdjęcia",
    "products.detail.sellerFallback": "Sprzedawca hurtowy",
    "products.detail.net": "netto",
    "products.detail.gross": "brutto",
    "products.detail.vat": "VAT",
    "products.detail.pack": "Pack",
    "products.detail.netPrices": "Podane ceny są netto",
    "products.detail.outOfStock": "Brak w magazynie",
    "products.detail.inStock": "paczek dostępnych",
    "products.detail.variants": "Warianty",
    "products.detail.noVariant": "Bez wariantu — produkt podstawowy",
    "products.detail.quantityPacks": "Ilość — packi",
    "products.detail.add": "Dodaj",
    "products.detail.packs": "packów",
    "products.detail.packSingle": "pack",
    "products.detail.buyingPacks": "Kupujesz packi, nie sztuki.",
    "products.detail.piecesInPack": "szt. w packu",
    "products.detail.grossForQty": "brutto",
    "products.detail.description": "Opis",
    "products.detail.productNotFound": "Nie znaleziono produktu",
    "products.detail.browseCategories": "← Przeglądaj kategorie",
    // product form
    "productForm.name": "Nazwa *",
    "productForm.slug": "Slug (auto jeśli puste)",
    "productForm.slugPlaceholder": "auto",
    "productForm.description": "Opis",
    "productForm.category": "Kategoria *",
    "productForm.categoryPlaceholder": "— Wybierz —",
    "productForm.categoryHint": "Wybierz kategorię liścia (np. Elektronika → Telefony). Zgłoś brakującą przez stronę Kategorie.",
    "productForm.packSize": "Rozmiar packa *",
    "productForm.priceNet": "Cena netto *",
    "productForm.vat": "VAT %",
    "productForm.grossApprox": "Brutto ≈",
    "productForm.stockQty": "Stan magazynowy",
    "productForm.stockStatus": "Status magazynowy",
    "productForm.inStock": "w magazynie",
    "productForm.outOfStock": "brak",
    "productForm.active": "Aktywny (odznacz aby archiwizować)",
    "productForm.images": "Zdjęcia",
    "productForm.imagesHint": "Wgraj do",
    "productForm.imagesHint2": "lub wybierz z",
    "productForm.imagesHint3": "(folder testowy).",
    "productForm.uploadImage": "Wgraj zdjęcie",
    "productForm.uploading": "Wgrywanie…",
    "productForm.or": "lub",
    "productForm.noTestImages": "Brak obrazów testowych w assets/test-images",
    "productForm.pasteUrl": "Lub wklej URL obrazu ręcznie",
    "productForm.pastePlaceholder": "https://... lub /uploads/products/xxx.jpg",
    "productForm.addUrl": "Dodaj URL",
    "productForm.variants": "Warianty (rozmiar/kolor)",
    "productForm.addVariant": "+ Dodaj wariant",
    "productForm.noVariants": "Brak wariantów. Produkt sprzedawany jako pojedyncze SKU.",
    "productForm.sku": "SKU *",
    "productForm.optionName": "Nazwa opcji",
    "productForm.optionValue": "Wartość",
    "productForm.priceOverride": "Nadpisanie ceny",
    "productForm.saving": "Zapisywanie…",
    "productForm.errorName": "Nazwa wymagana",
    "productForm.errorCategory": "Kategoria wymagana",
    "productForm.errorPack": "Rozmiar packa >=1",
    "productForm.optionNamePlaceholder": "rozmiar/kolor",
    "productForm.optionValuePlaceholder": "XL / Czerwony",
    "productForm.netPlaceholder": "netto",
    "common.loadingText": "Ładowanie…",
    "common.back": "← Wróć",
    "common.notFound": "Nie znaleziono",
  },
  en: {
    "header.b2bOnly": "B2B only — orders for business entities",
    "header.b2bShort": "B2B only",
    "header.categories": "Categories",
    "header.shippingCosts": "Shipping costs",
    "header.terms": "Terms",
    "header.login": "Sign in",
    "header.searchPlaceholder": "Search — product, category, SKU…",
    "header.search": "Search",
    "header.cart": "Cart",
    "header.net": "net",
    "header.netLong": "Prices are net",
    "header.loginBtn": "Log in",
    "header.signup": "Sign up",
    "header.logout": "Sign out",
    "header.new": "New",
    "header.sale": "Sale",
    "header.bestsellers": "Bestsellers",
    "header.allCategories": "All categories",
    "header.products": "Products",
    "header.deliveryNote": "Delivery: to be determined • Prices are",
    "header.all": "All →",
    "home.bannerBusiness": "Please note: only business entities can place orders in our wholesale store.",
    "home.bannerSuffix": "— CentrumHurt pattern, modernized. B2B verified at checkout.",
    "home.becomeSeller": "Become a seller →",
    "home.badge": "WÓLKA KOSOWSKA WHOLESALE — ONLINE",
    "home.heroTitle1": "B2B wholesale.",
    "home.heroTitle2": "Packs, not pieces.",
    "home.heroDesc": "Modernized CentrumHurt: clean catalog, pack pricing net + gross, subcategory sidebar like the reference — but faster, lighter, mobile-first.",
    "home.browseCategories": "Browse categories",
    "home.newBestsellers": "New / Bestsellers",
    "home.delivery": "Delivery: to be determined",
    "home.pricesNet": "Prices are",
    "home.trustShippingTitle": "Shipping costs",
    "home.trustShippingDesc": "To be determined • COD / invoice",
    "home.trustB2BTitle": "B2B only",
    "home.trustB2BDesc": "VAT ID verified — like CentrumHurt",
    "home.trustNetTitle": "Net prices",
    "home.trustNetDesc": "Gross = net + VAT • pack pricing",
    "home.featuredTitle": "Wholesale categories",
    "home.featuredDesc": "CentrumHurt taxonomy — modern cards, subcategory preview.",
    "home.viewAll": "View all →",
    "home.viewAllPl": "View all →",
    "home.browseProducts": "Browse products",
    "home.subcategories": "subcategories",
    "home.arrivalsTitle": "New & Bestsellers",
    "home.arrivalsDesc": "Latest pack products — like CentrumHurt “New” section.",
    "footer.title": "Wholesale Marketplace",
    "footer.desc": "Wólka Kosowska inspired • modern B2B • pack-quantity cart • COD.",
    "footer.contact": "Contact",
    "footer.info": "Information",
    "footer.faq": "FAQ",
    "home.noCategories": "No categories yet — admin at /admin/categories.",
    "product.noImage": "No image",
    "product.noCategory": "Uncategorized",
    "product.gross": "gross",
    "product.net": "net",
    "product.pack": "Pack",
    "product.out": "Out of stock",
    "product.available": "packs available",
    "product.add": "Add",
    "product.netPricesNote": "Net prices — delivery to be determined",
    "search.noResults": "No products found.",
    "search.resultsFor": "Results for",
    "categorySidebar.title": "Wholesale categories",
    "categorySidebar.all": "All products",
    "common.loading": "Loading…",
    "common.allProducts": "All products",
    "cart.title": "Cart",
    "cart.packs": "packs",
    "cart.empty": "Your cart is empty.",
    "cart.browse": "Browse categories",
    "checkout.shipping": "Shipping address",
    "checkout.codNote": "Cash on delivery / invoice",
    "product.homeAll": "Home",
    "auth.login.title": "Sign in to your account",
    "auth.login.or": "Or",
    "auth.login.createAccount": "create a new account",
    "auth.login.emailLabel": "Email address",
    "auth.login.emailPlaceholder": "Email address",
    "auth.login.passwordLabel": "Password",
    "auth.login.passwordPlaceholder": "Password",
    "auth.login.signIn": "Sign in",
    "auth.login.signingIn": "Signing in...",
    "auth.login.registerSeller": "Register as a Seller",
    "auth.login.loading": "Loading...",
    "auth.signup.title": "Create your account",
    "auth.signup.alreadyHave": "Already have an account?",
    "auth.signup.signIn": "Sign in",
    "auth.signup.fullNameLabel": "Full name",
    "auth.signup.fullNamePlaceholder": "Full name",
    "auth.signup.emailLabel": "Email address",
    "auth.signup.emailPlaceholder": "Email address",
    "auth.signup.passwordLabel": "Password",
    "auth.signup.passwordPlaceholder": "Password (min 8 characters)",
    "auth.signup.confirmPasswordLabel": "Confirm password",
    "auth.signup.confirmPasswordPlaceholder": "Confirm password",
    "auth.signup.registerAs": "Register as",
    "auth.signup.buyer": "Buyer",
    "auth.signup.seller": "Seller",
    "auth.signup.sellerNote": "Seller accounts require admin approval. After registering, you'll need to provide business information.",
    "auth.signup.creating": "Creating account...",
    "auth.signup.create": "Create account",
    "auth.signup.errorMismatch": "Passwords do not match",
    "auth.signup.errorLength": "Password must be at least 8 characters",
    "auth.registerSeller.title": "Register as a Seller",
    "auth.registerSeller.alreadyHave": "Already have an account?",
    "auth.registerSeller.signIn": "Sign in",
    "auth.registerSeller.accountInfo": "Account Information",
    "auth.registerSeller.fullName": "Full Name",
    "auth.registerSeller.fullNamePlaceholder": "Full name",
    "auth.registerSeller.email": "Email Address",
    "auth.registerSeller.emailPlaceholder": "Email address",
    "auth.registerSeller.password": "Password",
    "auth.registerSeller.passwordPlaceholder": "Password (min 8 characters)",
    "auth.registerSeller.confirmPassword": "Confirm Password",
    "auth.registerSeller.confirmPasswordPlaceholder": "Confirm password",
    "auth.registerSeller.businessInfo": "Business Information",
    "auth.registerSeller.businessName": "Business Name",
    "auth.registerSeller.businessNamePlaceholder": "Your business name",
    "auth.registerSeller.taxId": "Tax ID (VAT/NIP)",
    "auth.registerSeller.businessAddress": "Business Address",
    "auth.registerSeller.phone": "Phone Number",
    "auth.registerSeller.optional": "Optional",
    "auth.registerSeller.notePrefix": "Note:",
    "auth.registerSeller.note": "Seller accounts require admin approval. After submitting, your application will be reviewed. You'll be notified once a decision is made.",
    "auth.registerSeller.submitting": "Submitting application...",
    "auth.registerSeller.submit": "Submit Application",
    "auth.registerSeller.errorBusinessName": "Business name is required",
    "auth.registerSeller.errorMismatch": "Passwords do not match",
    "auth.registerSeller.errorLength": "Password must be at least 8 characters",
    "seller.dashboard.panel": "Seller Panel",
    "seller.dashboard.approved": "Approved Seller",
    "seller.dashboard.signOut": "Sign out",
    "seller.dashboard.title": "Seller Dashboard",
    "seller.dashboard.welcome": "Welcome",
    "seller.dashboard.categories": "Categories",
    "seller.dashboard.categoriesDesc": "Browse taxonomy and request new categories.",
    "seller.dashboard.manageProducts": "Manage Products",
    "seller.dashboard.manageProductsDesc": "Add, edit, and manage your product catalog.",
    "seller.dashboard.orders": "Orders",
    "seller.dashboard.ordersDesc": "View and manage incoming orders.",
    "seller.dashboard.businessProfile": "Business Profile",
    "seller.dashboard.businessProfileDesc": "Update your business information.",
    "seller.dashboard.quickStats": "Quick Stats",
    "seller.dashboard.totalProducts": "Total Products",
    "seller.dashboard.pendingOrders": "Pending Orders",
    "seller.dashboard.completedOrders": "Completed Orders",
    "seller.dashboard.revenue": "Revenue",
    "seller.pending.notFound": "Seller Profile Not Found",
    "seller.pending.notFoundDesc": "Please complete your seller registration.",
    "seller.pending.registerSeller": "Register as Seller",
    "seller.pending.statusTitle": "Seller Application Status",
    "seller.pending.businessInfo": "Business Information",
    "seller.pending.businessName": "Business Name",
    "seller.pending.taxId": "Tax ID",
    "seller.pending.phone": "Phone",
    "seller.pending.businessAddress": "Business Address",
    "seller.pending.rejectionReason": "Rejection Reason",
    "seller.pending.nextSteps": "Next Steps",
    "seller.pending.pendingReview": "Your application is under review by our admin team.",
    "seller.pending.notify": "You'll receive a notification once a decision is made.",
    "seller.pending.reviewTime": "Typical review time: 1-2 business days",
    "seller.pending.approvedTitle": "Congratulations! Your seller account has been approved.",
    "seller.pending.approvedDesc": "You can now access the seller panel to manage your products and orders.",
    "seller.pending.goDashboard": "Go to Seller Dashboard",
    "seller.pending.rejectedDesc1": "Your application was not approved. Please review the rejection reason above.",
    "seller.pending.rejectedDesc2": "You can submit a new application with corrected information.",
    "seller.pending.submitNew": "Submit New Application",
    "seller.pending.backHome": "← Back to Home",
    "seller.pending.statusPending": "pending",
    "seller.pending.statusApproved": "approved",
    "seller.pending.statusRejected": "rejected",
    "seller.products.panel": "Seller Panel",
    "seller.products.dashboard": "Dashboard",
    "seller.products.products": "Products",
    "seller.products.categories": "Categories",
    "seller.products.title": "My Products",
    "seller.products.desc": "Manage your catalog — pack size, pricing, stock, images.",
    "seller.products.addProduct": "+ Add Product",
    "seller.products.empty": "No products yet. Create your first pack product.",
    "seller.products.emptyAdd": "Add Product",
    "seller.products.thProduct": "Product",
    "seller.products.thCategory": "Category",
    "seller.products.thPackPrice": "Pack & Price",
    "seller.products.thStock": "Stock",
    "seller.products.thStatus": "Status",
    "seller.products.thActions": "Actions",
    "seller.products.noImg": "No img",
    "seller.products.archivedLabel": "(archived)",
    "seller.products.pack": "Pack",
    "seller.products.net": "Net",
    "seller.products.gross": "Gross",
    "seller.products.vat": "VAT",
    "seller.products.toggleStock": "Toggle stock",
    "seller.products.active": "active",
    "seller.products.archived": "archived",
    "seller.products.edit": "Edit",
    "seller.products.archive": "Archive",
    "seller.products.unarchive": "Unarchive",
    "seller.products.delete": "Delete",
    "seller.products.confirmDelete": "Delete product? This cannot be undone.",
    "seller.products.inStock": "in stock",
    "seller.products.outOfStock": "out",
    "seller.products.stockIn": "in_stock",
    "seller.products.stockOut": "out_of_stock",
    "seller.products.new.panel": "Seller Panel",
    "seller.products.new.productsLink": "Products",
    "seller.products.new.back": "← Back to products",
    "seller.products.new.title": "Add Product",
    "seller.products.new.desc": "Pack pricing, category, stock and images. Seller must be approved.",
    "seller.products.new.createLabel": "Create product",
    "seller.products.edit.title": "Edit Product",
    "seller.products.edit.productsLink": "Products",
    "seller.products.edit.back": "← Back",
    "seller.products.edit.notFound": "Not found",
    "seller.products.edit.saveLabel": "Save changes",
    "seller.products.edit.loadingFailed": "Failed to load",
    "seller.categories.panel": "Seller Panel",
    "seller.categories.dashboard": "Dashboard",
    "seller.categories.categories": "Categories",
    "seller.categories.signOut": "Sign out",
    "seller.categories.available": "Available Categories",
    "seller.categories.availableDesc": "Taxonomy is centrally controlled. Pick from the tree when listing products; request additions if needed.",
    "seller.categories.total": "categories total • inactive hidden",
    "seller.categories.requestTitle": "Request New Category",
    "seller.categories.requestDesc": "Propose a new top-level category or subcategory. Admin will review.",
    "seller.categories.name": "Name *",
    "seller.categories.namePlaceholder": "e.g. Garden Tools",
    "seller.categories.slug": "Slug (optional, auto from name)",
    "seller.categories.slugPlaceholder": "garden-tools",
    "seller.categories.parent": "Parent category (leave empty for top-level)",
    "seller.categories.topLevel": "— Top-level —",
    "seller.categories.description": "Reason / description",
    "seller.categories.descriptionPlaceholder": "Why is this category needed?",
    "seller.categories.submitting": "Submitting...",
    "seller.categories.submit": "Submit request",
    "seller.categories.myRequests": "My Requests",
    "seller.categories.noRequests": "No requests yet.",
    "seller.categories.under": "Under",
    "seller.categories.topLevelLabel": "Top-level",
    "seller.categories.rejected": "Rejected:",
    "seller.categories.nameRequired": "Name is required",
    "seller.categories.requestSubmitted": "Request submitted for",
    "seller.categories.pendingApproval": "— pending admin approval.",
    "seller.categories.signOutLabel": "Sign out",
    "buyer.dashboard.panel": "Wholesale Marketplace",
    "buyer.dashboard.signOut": "Sign out",
    "buyer.dashboard.heading": "Buyer Dashboard",
    "buyer.dashboard.welcome": "Welcome back",
    "buyer.dashboard.browseProducts": "Browse Products",
    "buyer.dashboard.browseProductsDesc": "Explore our wholesale catalog and find products for your business.",
    "buyer.dashboard.myOrders": "My Orders",
    "buyer.dashboard.myOrdersDesc": "View and track your purchase orders.",
    "buyer.dashboard.accountSettings": "Account Settings",
    "buyer.dashboard.accountSettingsDesc": "Manage your profile and preferences.",
    "buyer.orders.title": "My orders",
    "buyer.orders.desc": "Pack-quantity orders • COD • statuses pending → delivered",
    "buyer.orders.empty": "No orders yet.",
    "buyer.orders.browse": "Browse products →",
    "buyer.orders.order": "Order #",
    "buyer.orders.gross": "Gross",
    "buyer.orders.net": "net",
    "buyer.orders.ship": "Ship:",
    "buyer.orders.pack": "pack",
    "admin.dashboard.panel": "Admin Panel",
    "admin.dashboard.admin": "Admin",
    "admin.dashboard.signOut": "Sign out",
    "admin.dashboard.title": "Seller Approvals",
    "admin.dashboard.desc": "Review and approve/reject pending seller applications",
    "admin.dashboard.manageCategories": "Manage Categories →",
    "admin.dashboard.noPending": "No pending sellers",
    "admin.dashboard.allReviewed": "All seller applications have been reviewed.",
    "admin.dashboard.thBusiness": "Business Name",
    "admin.dashboard.thApplicant": "Applicant",
    "admin.dashboard.thEmail": "Email",
    "admin.dashboard.thApplied": "Applied",
    "admin.dashboard.thStatus": "Status",
    "admin.dashboard.thActions": "Actions",
    "admin.dashboard.approve": "Approve",
    "admin.dashboard.reject": "Reject",
    "admin.dashboard.approving": "Approving...",
    "admin.dashboard.rejecting": "Rejecting...",
    "admin.dashboard.rejectionPrompt": "Please provide a rejection reason:",
    "admin.dashboard.approveFailed": "Failed to approve seller:",
    "admin.dashboard.rejectFailed": "Failed to reject seller:",
    "admin.categories.panel": "Admin Panel",
    "admin.categories.sellers": "Sellers",
    "admin.categories.categories": "Categories",
    "admin.categories.signOut": "Sign out",
    "admin.categories.treeTitle": "Category Tree",
    "admin.categories.topLevel": "+ Top-level",
    "admin.categories.edit": "Edit",
    "admin.categories.subcategory": "+ Subcategory",
    "admin.categories.delete": "Delete",
    "admin.categories.confirmDelete": "Delete this category? This cannot be undone if it has no children/products.",
    "admin.categories.editCategory": "Edit category",
    "admin.categories.newCategory": "New category",
    "admin.categories.name": "Name *",
    "admin.categories.slug": "Slug (auto if blank)",
    "admin.categories.slugAuto": "electronics",
    "admin.categories.parent": "Parent",
    "admin.categories.topLevelOption": "— Top-level —",
    "admin.categories.active": "Active",
    "admin.categories.save": "Save",
    "admin.categories.create": "Create",
    "admin.categories.cancel": "Cancel",
    "admin.categories.pendingTitle": "Pending Category Requests",
    "admin.categories.pendingDesc": "Sellers request new categories/subcategories; approve to add to tree.",
    "admin.categories.noPending": "No pending requests.",
    "admin.categories.approve": "Approve",
    "admin.categories.reject": "Reject",
    "admin.categories.rejectionReason": "Rejection reason:",
    "admin.categories.recentDecisions": "Recent decisions",
    "admin.categories.by": "by",
    "admin.categories.topLevelFallback": "(top-level)",
    "cart.emptyTitle": "Your cart is empty.",
    "cart.countPacks": "packs",
    "cart.packQuantityBased": "Pack-quantity based. You buy packs, not single units.",
    "cart.pack": "Pack",
    "cart.gross": "gross",
    "cart.net": "net",
    "cart.remove": "Remove",
    "cart.netTotal": "Net total",
    "cart.grossTotal": "Gross total",
    "cart.codNoteDetail": "Incl. VAT. COD / manual invoice for MVP — no payment gateway.",
    "cart.proceedCheckout": "Proceed to checkout",
    "cart.continueShopping": "Continue shopping",
    "cart.noImg": "No img",
    "cart.vatNote": "Incl. VAT. COD / manual invoice",
    "checkout.title": "Checkout",
    "checkout.codDesc": "COD / manual invoice — no payment gateway for MVP.",
    "checkout.cartEmpty": "Cart empty.",
    "checkout.browseProducts": "Browse products →",
    "checkout.errorCartEmpty": "Cart empty",
    "checkout.errorAddress": "Shipping address required",
    "checkout.errorBuyerOnly": "Only buyers can place orders. Switch to buyer account.",
    "checkout.signInPrompt": "Please sign in as buyer to place order. You can still fill address then sign in.",
    "checkout.signIn": "sign in",
    "checkout.shippingAddress": "Shipping address *",
    "checkout.shippingPlaceholder": "Street, city, postal code, country",
    "checkout.notes": "Notes (optional)",
    "checkout.notesPlaceholder": "Delivery notes, invoice request…",
    "checkout.net": "Net",
    "checkout.grossCOD": "Gross (COD)",
    "checkout.payNote": "You will pay on delivery / manual invoice. Order status starts as pending.",
    "checkout.placing": "Placing…",
    "checkout.placeOrder": "Place order —",
    "checkout.codSuffix": "COD",
    "checkout.orderSummary": "Order summary —",
    "checkout.itemsPackBased": "items, pack-quantity based",
    "checkout.editCart": "Edit cart",
    "checkout.success.title": "Order placed",
    "checkout.success.desc": "Thank you — COD/manual invoice. Status: pending.",
    "checkout.success.order": "Order #",
    "checkout.success.totalNet": "Total net:",
    "checkout.success.totalGross": "Total gross:",
    "checkout.success.shipping": "Shipping:",
    "checkout.success.continueShopping": "Continue shopping",
    "checkout.success.myOrders": "My orders",
    "checkout.success.loading": "Loading…",
    "search.titleSearch": "Search:",
    "search.titleAll": "All products",
    "search.desc": "Search by name, description, category — simple ILIKE (Postgres full-text ready).",
    "search.searching": "Searching…",
    "search.noResultsFor": "No results for",
    "categories.allTitle": "All categories",
    "categories.allDesc": "Browse by category — subcategory sidebar like centrumhurt.pl.",
    "categories.subcategoriesLabel": "subcategories",
    "categories.allProductsTitle": "All products",
    "categories.loading": "Loading…",
    "categories.slug.breadcrumbCategories": "Categories",
    "categories.slug.packPricing": "Pack pricing • net/gross • VAT included",
    "categories.slug.productsCount": "products",
    "categories.slug.noProducts": "No products in this category yet.",
    "categories.slug.categoryNotFound": "Category not found",
    "categories.slug.allCategories": "← All categories",
    "products.detail.breadcrumbCategories": "Categories",
    "products.detail.noImage": "No image",
    "products.detail.sellerFallback": "Wholesale seller",
    "products.detail.net": "net",
    "products.detail.gross": "gross",
    "products.detail.vat": "VAT",
    "products.detail.pack": "Pack",
    "products.detail.netPrices": "Net prices shown",
    "products.detail.outOfStock": "Out of stock",
    "products.detail.inStock": "packs available",
    "products.detail.variants": "Variants",
    "products.detail.noVariant": "No variant — base product",
    "products.detail.quantityPacks": "Quantity — packs",
    "products.detail.add": "Add",
    "products.detail.packs": "packs",
    "products.detail.packSingle": "pack",
    "products.detail.buyingPacks": "You buy packs, not pieces.",
    "products.detail.piecesInPack": "pcs per pack",
    "products.detail.grossForQty": "gross",
    "products.detail.description": "Description",
    "products.detail.productNotFound": "Product not found",
    "products.detail.browseCategories": "← Browse categories",
    "productForm.name": "Name *",
    "productForm.slug": "Slug (auto if blank)",
    "productForm.slugPlaceholder": "auto",
    "productForm.description": "Description",
    "productForm.category": "Category *",
    "productForm.categoryPlaceholder": "— Select —",
    "productForm.categoryHint": "Pick leaf category (e.g. Electronics → Mobile Phones). Request new via Categories page if missing.",
    "productForm.packSize": "Pack size *",
    "productForm.priceNet": "Price net *",
    "productForm.vat": "VAT %",
    "productForm.grossApprox": "Gross ≈",
    "productForm.stockQty": "Stock qty",
    "productForm.stockStatus": "Stock status",
    "productForm.inStock": "in_stock",
    "productForm.outOfStock": "out_of_stock",
    "productForm.active": "Active (archive if unchecked)",
    "productForm.images": "Images",
    "productForm.imagesHint": "Upload to",
    "productForm.imagesHint2": "or pick from",
    "productForm.imagesHint3": "(test folder).",
    "productForm.uploadImage": "Upload image",
    "productForm.uploading": "Uploading...",
    "productForm.or": "or",
    "productForm.noTestImages": "No test images in assets/test-images",
    "productForm.pasteUrl": "Or paste image URL manually",
    "productForm.pastePlaceholder": "https://... or /uploads/products/xxx.jpg",
    "productForm.addUrl": "Add URL",
    "productForm.variants": "Variants (size/color)",
    "productForm.addVariant": "+ Add variant",
    "productForm.noVariants": "No variants. Product sold as single SKU.",
    "productForm.sku": "SKU *",
    "productForm.optionName": "Option name",
    "productForm.optionValue": "Value",
    "productForm.priceOverride": "Price override",
    "productForm.saving": "Saving...",
    "productForm.errorName": "Name required",
    "productForm.errorCategory": "Category required",
    "productForm.errorPack": "Pack size >=1",
    "productForm.optionNamePlaceholder": "size/color",
    "productForm.optionValuePlaceholder": "XL / Red",
    "productForm.netPlaceholder": "net",
    "common.loadingText": "Loading…",
    "common.back": "← Back",
    "common.notFound": "Not found",
  },
};

interface Ctx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<Ctx | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("pl");

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Lang | null;
    if (saved === "pl" || saved === "en") {
      setLangState(saved);
    } else {
      // auto-detect: if browser is en, use en else pl
      const nav = navigator.language.toLowerCase();
      if (nav.startsWith("en")) setLangState("en");
    }
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  const t = (key: string) => dictionaries[lang][key] ?? key;

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
